phpsnow:
  developer-mode: ${PHP_SNOW_APP_MODE:production}
  default:
    animation-duration-sec: '300'
    fps: '33'
    width: '180'
    height: '40'
    preset-name: slideshow:random
  allowed-origins:
    http://127.0.0.1:8181/
    http://127.0.0.1:3000/
    http://localhost:8181/
    http://localhost:3000/
  threads:
    max-pool-size: '11'
    queue-capacity: '24'
    timeout: '3600'
    core-pool-size: '6'
  buffer-size-in-milliseconds: '2000'
  bootstrap: ../run
logging:
  level:
    techbit:
      snow: TRACE
    root: WARN
server:
  error:
    include-stacktrace: always
    include-exception: 'true'
    include-binding-errors: always
    include-message: always
