name: deploy-to-docker-hub

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Git Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mmmostrowski/php-snow:latest
